// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybvfsxsapsshhtqpvukr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlidmZzeHNhcHNzaGh0cXB2dWtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMzA1NzMsImV4cCI6MjA1NzgwNjU3M30.n82ENpFqZ4CcBiNAjJXDehAiaLA-xboWJX-OIo2FKv4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});