-- Add ticket_prices_html column to concerts and festivals tables
-- This will store the HTML generated by the ticket price extractor

ALTER TABLE public.concerts 
ADD COLUMN ticket_prices_html text;

ALTER TABLE public.festivals 
ADD COLUMN ticket_prices_html text;

-- Add comment for documentation
COMMENT ON COLUMN public.concerts.ticket_prices_html IS 'HTML block containing extracted ticket prices from ticket vendors';
COMMENT ON COLUMN public.festivals.ticket_prices_html IS 'HTML block containing extracted ticket prices from ticket vendors';