// deno-lint-ignore-file
// @ts-nocheck
// Returns an iCal/.ics calendar feed of the requesting user's accreditation deadlines.
// Subscribed once from a phone calendar app, the device receives native reminders.
//
// Auth model: ?token=<userId>.<hex_hmac> in URL. Token is generated by `calendar-token`.
// The HMAC secret lives in CALENDAR_HMAC_SECRET env (Supabase secret).
import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.52.0';

const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const CALENDAR_HMAC_SECRET = Deno.env.get('CALENDAR_HMAC_SECRET') || SUPABASE_SERVICE_ROLE_KEY;

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

async function hmacHex(secret: string, message: string): Promise<string> {
  const enc = new TextEncoder();
  const key = await crypto.subtle.importKey(
    'raw',
    enc.encode(secret),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign']
  );
  const sig = await crypto.subtle.sign('HMAC', key, enc.encode(message));
  return Array.from(new Uint8Array(sig))
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');
}

function escapeIcs(s: string): string {
  if (!s) return '';
  return s
    .replace(/\\/g, '\\\\')
    .replace(/\n/g, '\\n')
    .replace(/,/g, '\\,')
    .replace(/;/g, '\\;');
}

function dateOnly(date: Date): string {
  return [
    date.getUTCFullYear(),
    String(date.getUTCMonth() + 1).padStart(2, '0'),
    String(date.getUTCDate()).padStart(2, '0'),
  ].join('');
}

function utcStamp(date: Date): string {
  return (
    [
      date.getUTCFullYear(),
      String(date.getUTCMonth() + 1).padStart(2, '0'),
      String(date.getUTCDate()).padStart(2, '0'),
    ].join('') +
    'T' +
    [
      String(date.getUTCHours()).padStart(2, '0'),
      String(date.getUTCMinutes()).padStart(2, '0'),
      String(date.getUTCSeconds()).padStart(2, '0'),
    ].join('') +
    'Z'
  );
}

const STATUS_ES: Record<string, string> = {
  draft: 'Borrador',
  pending: 'Pendiente',
  submitted: 'Enviada',
  approved: 'Aprobada',
  rejected: 'Rechazada',
  expired: 'Vencida',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders });

  try {
    const url = new URL(req.url);
    const token = url.searchParams.get('token');
    if (!token || !token.includes('.')) {
      return new Response('Token inválido', { status: 401, headers: corsHeaders });
    }

    const [userId, sig] = token.split('.');
    const expected = await hmacHex(CALENDAR_HMAC_SECRET, userId);
    if (sig !== expected) {
      return new Response('Firma inválida', { status: 401, headers: corsHeaders });
    }

    const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
      auth: { persistSession: false },
    });

    // Verify user exists and is an admin (admins see all accreditations).
    // Non-admin users only see ones they're assigned to or created.
    const { data: profile } = await supabase
      .from('profiles')
      .select('id, role')
      .eq('id', userId)
      .maybeSingle();

    if (!profile) {
      return new Response('Usuario no encontrado', { status: 404, headers: corsHeaders });
    }

    let accs: any[] = [];
    if (profile.role === 'admin') {
      const { data } = await supabase
        .from('accreditations')
        .select('*')
        .order('deadline', { ascending: true });
      accs = data ?? [];
    } else {
      const { data: assignments } = await supabase
        .from('event_team_assignments')
        .select('accreditation_id')
        .eq('user_id', userId);
      const assignedIds = (assignments ?? []).map((a) => a.accreditation_id);

      const { data: own } = await supabase
        .from('accreditations')
        .select('*')
        .eq('created_by', userId);

      const { data: assigned } =
        assignedIds.length > 0
          ? await supabase.from('accreditations').select('*').in('id', assignedIds)
          : { data: [] };

      const map = new Map<string, any>();
      [...(own ?? []), ...(assigned ?? [])].forEach((a) => map.set(a.id, a));
      accs = Array.from(map.values()).sort(
        (a, b) => new Date(a.deadline).getTime() - new Date(b.deadline).getTime()
      );
    }

    const now = new Date();
    const lines: string[] = [
      'BEGIN:VCALENDAR',
      'VERSION:2.0',
      'PRODID:-//Conciertos LATAM//Acreditaciones//ES',
      'CALSCALE:GREGORIAN',
      'METHOD:PUBLISH',
      'X-WR-CALNAME:Acreditaciones · Conciertos LATAM',
      'X-WR-CALDESC:Deadlines de acreditaciones del equipo de Conciertos LATAM',
      'X-WR-TIMEZONE:America/Bogota',
      'REFRESH-INTERVAL;VALUE=DURATION:PT1H',
      'X-PUBLISHED-TTL:PT1H',
    ];

    for (const a of accs) {
      // Deadline as an all-day event on its date
      const deadlineDate = new Date(a.deadline + 'T12:00:00Z');
      const nextDay = new Date(deadlineDate.getTime() + 24 * 60 * 60 * 1000);

      const summary = `Deadline · ${a.event_name}`;
      const descParts: string[] = [];
      descParts.push(`Estado: ${STATUS_ES[a.status] ?? a.status}`);
      if (a.event_date) {
        descParts.push(`Evento: ${a.event_date}`);
      }
      if (a.contact_name) {
        descParts.push(`Contacto: ${a.contact_name}`);
        if (a.contact_email) descParts.push(`Email: ${a.contact_email}`);
        if (a.contact_phone) descParts.push(`Teléfono: ${a.contact_phone}`);
      }
      if (a.proposal_url) descParts.push(`Propuesta: ${a.proposal_url}`);
      if (a.notes) descParts.push(`Notas: ${a.notes}`);

      lines.push('BEGIN:VEVENT');
      lines.push(`UID:accred-${a.id}@conciertoslatam.app`);
      lines.push(`DTSTAMP:${utcStamp(now)}`);
      lines.push(`DTSTART;VALUE=DATE:${dateOnly(deadlineDate)}`);
      lines.push(`DTEND;VALUE=DATE:${dateOnly(nextDay)}`);
      lines.push(`SUMMARY:${escapeIcs(summary)}`);
      lines.push(`DESCRIPTION:${escapeIcs(descParts.join('\n'))}`);
      if (a.venue_name) lines.push(`LOCATION:${escapeIcs(a.venue_name)}`);
      lines.push(`STATUS:${a.status === 'rejected' ? 'CANCELLED' : 'CONFIRMED'}`);
      lines.push(`URL:https://www.conciertoslatam.app/admin/operations`);
      lines.push('CATEGORIES:Acreditación');

      // Reminders — fire native phone alerts
      const alarms: Array<{ trigger: string; desc: string }> = [
        { trigger: '-P7D', desc: 'Deadline en 7 días' },
        { trigger: '-P3D', desc: 'Deadline en 3 días' },
        { trigger: '-P1D', desc: 'Deadline mañana' },
      ];
      for (const al of alarms) {
        lines.push('BEGIN:VALARM');
        lines.push('ACTION:DISPLAY');
        lines.push(`DESCRIPTION:${escapeIcs(al.desc)}: ${escapeIcs(a.event_name)}`);
        lines.push(`TRIGGER:${al.trigger}`);
        lines.push('END:VALARM');
      }

      lines.push('END:VEVENT');
    }

    lines.push('END:VCALENDAR');

    // ICS requires CRLF line endings
    const body = lines.join('\r\n') + '\r\n';

    return new Response(body, {
      status: 200,
      headers: {
        ...corsHeaders,
        'Content-Type': 'text/calendar; charset=utf-8',
        'Content-Disposition': 'inline; filename="acreditaciones.ics"',
        'Cache-Control': 'public, max-age=600',
      },
    });
  } catch (e) {
    console.error('calendar-ics error', e);
    return new Response('Error generando calendario', { status: 500, headers: corsHeaders });
  }
});
